/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export type AdminListUsersParams = {
page?: number;
/**
 * @nullable
 */
keyword?: string | null;
/**
 * @nullable
 */
role?: string | null;
};
