/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export interface AdminUser {
  id: string;
  email: string;
  display_name: string;
  role: string;
  is_dealer: boolean;
  listing_count: number;
  created_at: string;
}
