/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export interface AdminStats {
  total_users: number;
  total_dealers: number;
  total_listings: number;
  active_listings: number;
  pending_listings: number;
  total_reports: number;
  pending_reports: number;
  today_signups: number;
  today_listings: number;
}
