/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List and search vehicles
 */
export const listVehiclesQueryPageDefault = 1;
export const listVehiclesQueryLimitDefault = 20;
export const listVehiclesQuerySortDefault = `newest`;
export const listVehiclesQueryCurrencyDefault = `USD`;

export const ListVehiclesQueryParams = zod.object({
  "page": zod.coerce.number().default(listVehiclesQueryPageDefault),
  "limit": zod.coerce.number().default(listVehiclesQueryLimitDefault),
  "brand_id": zod.coerce.number().nullish(),
  "model_id": zod.coerce.number().nullish(),
  "vehicle_type_id": zod.coerce.number().nullish(),
  "condition_id": zod.coerce.number().nullish(),
  "fuel_type_id": zod.coerce.number().nullish(),
  "transmission_id": zod.coerce.number().nullish(),
  "region_id": zod.coerce.number().nullish(),
  "city_id": zod.coerce.number().nullish(),
  "year_min": zod.coerce.number().nullish(),
  "year_max": zod.coerce.number().nullish(),
  "price_min": zod.coerce.number().nullish(),
  "price_max": zod.coerce.number().nullish(),
  "mileage_max": zod.coerce.number().nullish(),
  "color_id": zod.coerce.number().nullish(),
  "seller_type": zod.union([zod.literal('individual'),zod.literal('dealer'),zod.literal(null)]).nullish(),
  "is_negotiable": zod.coerce.boolean().nullish(),
  "keyword": zod.coerce.string().nullish(),
  "sort": zod.enum(['newest', 'oldest', 'price_asc', 'price_desc', 'most_viewed', 'most_favorited']).default(listVehiclesQuerySortDefault),
  "featured_only": zod.coerce.boolean().nullish(),
  "currency": zod.coerce.string().default(listVehiclesQueryCurrencyDefault)
})

export const ListVehiclesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand": zod.string(),
  "model": zod.string(),
  "year": zod.number(),
  "price": zod.number(),
  "price_usd": zod.number().nullish(),
  "currency": zod.string(),
  "mileage": zod.number().nullish(),
  "condition": zod.string(),
  "city": zod.string(),
  "region": zod.string(),
  "cover_image": zod.string().nullish(),
  "is_negotiable": zod.boolean(),
  "is_featured": zod.boolean(),
  "seller_type": zod.string(),
  "views_count": zod.number(),
  "favorites_count": zod.number(),
  "is_favorited": zod.boolean().nullish(),
  "status": zod.string(),
  "created_at": zod.string()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number(),
  "total_pages": zod.number()
})


/**
 * @summary Create a new vehicle listing
 */
export const CreateVehicleBody = zod.object({
  "title": zod.string(),
  "brand_id": zod.number(),
  "model_id": zod.number(),
  "vehicle_type_id": zod.number(),
  "year": zod.number(),
  "mileage": zod.number().nullish(),
  "engine_size": zod.number().nullish(),
  "horsepower": zod.number().nullish(),
  "transmission_id": zod.number().nullish(),
  "fuel_type_id": zod.number().nullish(),
  "color_id": zod.number().nullish(),
  "condition_id": zod.number(),
  "vin": zod.string().nullish(),
  "price": zod.number(),
  "currency": zod.enum(['USD', 'IQD']),
  "is_negotiable": zod.boolean().optional(),
  "description": zod.string().nullish(),
  "region_id": zod.number(),
  "city_id": zod.number(),
  "latitude": zod.number().nullish(),
  "longitude": zod.number().nullish(),
  "status": zod.enum(['draft', 'active']).optional()
})

export const CreateVehicleResponse = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand_id": zod.number(),
  "model_id": zod.number(),
  "vehicle_type_id": zod.number(),
  "year": zod.number(),
  "mileage": zod.number().nullish(),
  "engine_size": zod.number().nullish(),
  "horsepower": zod.number().nullish(),
  "transmission_id": zod.number().nullish(),
  "fuel_type_id": zod.number().nullish(),
  "drive_type_id": zod.number().nullish(),
  "color_id": zod.number().nullish(),
  "condition_id": zod.number(),
  "vin": zod.string().nullish(),
  "price": zod.number(),
  "currency": zod.string(),
  "is_negotiable": zod.boolean(),
  "description": zod.string().nullish(),
  "region_id": zod.number(),
  "city_id": zod.number(),
  "latitude": zod.number().nullish(),
  "longitude": zod.number().nullish(),
  "status": zod.string(),
  "owner_id": zod.string(),
  "dealer_id": zod.string().nullish(),
  "created_at": zod.string(),
  "updated_at": zod.string()
})


/**
 * @summary Get featured vehicles for the landing page
 */
export const listFeaturedVehiclesQueryLimitDefault = 8;

export const ListFeaturedVehiclesQueryParams = zod.object({
  "limit": zod.coerce.number().default(listFeaturedVehiclesQueryLimitDefault)
})

export const ListFeaturedVehiclesResponseItem = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand": zod.string(),
  "model": zod.string(),
  "year": zod.number(),
  "price": zod.number(),
  "price_usd": zod.number().nullish(),
  "currency": zod.string(),
  "mileage": zod.number().nullish(),
  "condition": zod.string(),
  "city": zod.string(),
  "region": zod.string(),
  "cover_image": zod.string().nullish(),
  "is_negotiable": zod.boolean(),
  "is_featured": zod.boolean(),
  "seller_type": zod.string(),
  "views_count": zod.number(),
  "favorites_count": zod.number(),
  "is_favorited": zod.boolean().nullish(),
  "status": zod.string(),
  "created_at": zod.string()
})
export const ListFeaturedVehiclesResponse = zod.array(ListFeaturedVehiclesResponseItem)


/**
 * @summary Get latest vehicles for the landing page
 */
export const listLatestVehiclesQueryLimitDefault = 12;

export const ListLatestVehiclesQueryParams = zod.object({
  "limit": zod.coerce.number().default(listLatestVehiclesQueryLimitDefault)
})

export const ListLatestVehiclesResponseItem = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand": zod.string(),
  "model": zod.string(),
  "year": zod.number(),
  "price": zod.number(),
  "price_usd": zod.number().nullish(),
  "currency": zod.string(),
  "mileage": zod.number().nullish(),
  "condition": zod.string(),
  "city": zod.string(),
  "region": zod.string(),
  "cover_image": zod.string().nullish(),
  "is_negotiable": zod.boolean(),
  "is_featured": zod.boolean(),
  "seller_type": zod.string(),
  "views_count": zod.number(),
  "favorites_count": zod.number(),
  "is_favorited": zod.boolean().nullish(),
  "status": zod.string(),
  "created_at": zod.string()
})
export const ListLatestVehiclesResponse = zod.array(ListLatestVehiclesResponseItem)


/**
 * @summary Get vehicle details
 */
export const GetVehicleParams = zod.object({
  "id": zod.coerce.string()
})

export const GetVehicleResponse = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "logo_url": zod.string().nullish(),
  "listing_count": zod.number().nullish()
}),
  "model": zod.object({
  "id": zod.number(),
  "brand_id": zod.number(),
  "name": zod.string(),
  "listing_count": zod.number().nullish()
}),
  "vehicle_type": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string(),
  "icon": zod.string().nullish(),
  "listing_count": zod.number().nullish()
}),
  "year": zod.number(),
  "mileage": zod.number().nullish(),
  "engine_size": zod.number().nullish(),
  "horsepower": zod.number().nullish(),
  "transmission": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string()
}).optional(),
  "fuel_type": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string()
}).optional(),
  "color": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string(),
  "hex_code": zod.string().nullish()
}).optional(),
  "condition": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string()
}),
  "vin": zod.string().nullish(),
  "price": zod.number(),
  "price_usd": zod.number().nullish(),
  "price_iqd": zod.number().nullish(),
  "currency": zod.string(),
  "is_negotiable": zod.boolean(),
  "description": zod.string().nullish(),
  "region": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string(),
  "listing_count": zod.number().nullish()
}),
  "city": zod.object({
  "id": zod.number(),
  "region_id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string(),
  "listing_count": zod.number().nullish()
}),
  "latitude": zod.number().nullish(),
  "longitude": zod.number().nullish(),
  "images": zod.array(zod.object({
  "id": zod.string(),
  "url": zod.string(),
  "thumbnail_url": zod.string().nullish(),
  "is_cover": zod.boolean(),
  "sort_order": zod.number()
})),
  "seller": zod.object({
  "id": zod.string(),
  "display_name": zod.string(),
  "avatar_url": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "role": zod.string(),
  "created_at": zod.string()
}),
  "dealer": zod.object({
  "id": zod.string(),
  "business_name": zod.string(),
  "logo_url": zod.string().nullish(),
  "city": zod.string(),
  "is_verified": zod.boolean(),
  "listing_count": zod.number().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish()
}).optional(),
  "is_featured": zod.boolean(),
  "is_favorited": zod.boolean().nullish(),
  "views_count": zod.number(),
  "favorites_count": zod.number(),
  "status": zod.string(),
  "created_at": zod.string(),
  "updated_at": zod.string()
})


/**
 * @summary Update a vehicle listing
 */
export const UpdateVehicleParams = zod.object({
  "id": zod.coerce.string()
})

export const UpdateVehicleBody = zod.object({
  "title": zod.string().nullish(),
  "price": zod.number().nullish(),
  "currency": zod.string().nullish(),
  "is_negotiable": zod.boolean().nullish(),
  "description": zod.string().nullish(),
  "mileage": zod.number().nullish(),
  "status": zod.string().nullish(),
  "city_id": zod.number().nullish(),
  "region_id": zod.number().nullish()
})

export const UpdateVehicleResponse = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand_id": zod.number(),
  "model_id": zod.number(),
  "vehicle_type_id": zod.number(),
  "year": zod.number(),
  "mileage": zod.number().nullish(),
  "engine_size": zod.number().nullish(),
  "horsepower": zod.number().nullish(),
  "transmission_id": zod.number().nullish(),
  "fuel_type_id": zod.number().nullish(),
  "drive_type_id": zod.number().nullish(),
  "color_id": zod.number().nullish(),
  "condition_id": zod.number(),
  "vin": zod.string().nullish(),
  "price": zod.number(),
  "currency": zod.string(),
  "is_negotiable": zod.boolean(),
  "description": zod.string().nullish(),
  "region_id": zod.number(),
  "city_id": zod.number(),
  "latitude": zod.number().nullish(),
  "longitude": zod.number().nullish(),
  "status": zod.string(),
  "owner_id": zod.string(),
  "dealer_id": zod.string().nullish(),
  "created_at": zod.string(),
  "updated_at": zod.string()
})


/**
 * @summary Delete a vehicle listing
 */
export const DeleteVehicleParams = zod.object({
  "id": zod.coerce.string()
})

export const DeleteVehicleResponse = zod.void()


/**
 * @summary Get similar vehicles
 */
export const ListSimilarVehiclesParams = zod.object({
  "id": zod.coerce.string()
})

export const ListSimilarVehiclesResponseItem = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand": zod.string(),
  "model": zod.string(),
  "year": zod.number(),
  "price": zod.number(),
  "price_usd": zod.number().nullish(),
  "currency": zod.string(),
  "mileage": zod.number().nullish(),
  "condition": zod.string(),
  "city": zod.string(),
  "region": zod.string(),
  "cover_image": zod.string().nullish(),
  "is_negotiable": zod.boolean(),
  "is_featured": zod.boolean(),
  "seller_type": zod.string(),
  "views_count": zod.number(),
  "favorites_count": zod.number(),
  "is_favorited": zod.boolean().nullish(),
  "status": zod.string(),
  "created_at": zod.string()
})
export const ListSimilarVehiclesResponse = zod.array(ListSimilarVehiclesResponseItem)


/**
 * @summary Add image to a vehicle listing
 */
export const AddVehicleImageParams = zod.object({
  "id": zod.coerce.string()
})

export const AddVehicleImageBody = zod.object({
  "url": zod.string(),
  "thumbnail_url": zod.string().nullish(),
  "is_cover": zod.boolean().optional(),
  "sort_order": zod.number().optional()
})

export const AddVehicleImageResponse = zod.object({
  "id": zod.string(),
  "url": zod.string(),
  "thumbnail_url": zod.string().nullish(),
  "is_cover": zod.boolean(),
  "sort_order": zod.number()
})


/**
 * @summary Delete a vehicle image
 */
export const DeleteVehicleImageParams = zod.object({
  "id": zod.coerce.string(),
  "imageId": zod.coerce.string()
})

export const DeleteVehicleImageResponse = zod.void()


/**
 * @summary Publish a draft vehicle listing
 */
export const PublishVehicleParams = zod.object({
  "id": zod.coerce.string()
})

export const PublishVehicleResponse = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand_id": zod.number(),
  "model_id": zod.number(),
  "vehicle_type_id": zod.number(),
  "year": zod.number(),
  "mileage": zod.number().nullish(),
  "engine_size": zod.number().nullish(),
  "horsepower": zod.number().nullish(),
  "transmission_id": zod.number().nullish(),
  "fuel_type_id": zod.number().nullish(),
  "drive_type_id": zod.number().nullish(),
  "color_id": zod.number().nullish(),
  "condition_id": zod.number(),
  "vin": zod.string().nullish(),
  "price": zod.number(),
  "currency": zod.string(),
  "is_negotiable": zod.boolean(),
  "description": zod.string().nullish(),
  "region_id": zod.number(),
  "city_id": zod.number(),
  "latitude": zod.number().nullish(),
  "longitude": zod.number().nullish(),
  "status": zod.string(),
  "owner_id": zod.string(),
  "dealer_id": zod.string().nullish(),
  "created_at": zod.string(),
  "updated_at": zod.string()
})


/**
 * @summary Report a vehicle listing
 */
export const ReportVehicleParams = zod.object({
  "id": zod.coerce.string()
})

export const ReportVehicleBody = zod.object({
  "reason": zod.enum(['spam', 'fraud', 'inappropriate', 'duplicate', 'other']),
  "description": zod.string().nullish()
})

export const ReportVehicleResponse = zod.void()


/**
 * @summary List all brands
 */
export const listBrandsQueryWithCountsDefault = false;

export const ListBrandsQueryParams = zod.object({
  "vehicle_type_id": zod.coerce.number().nullish(),
  "with_counts": zod.coerce.boolean().default(listBrandsQueryWithCountsDefault)
})

export const ListBrandsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "logo_url": zod.string().nullish(),
  "listing_count": zod.number().nullish()
})
export const ListBrandsResponse = zod.array(ListBrandsResponseItem)


/**
 * @summary Get models for a brand
 */
export const ListBrandModelsParams = zod.object({
  "id": zod.coerce.number()
})

export const ListBrandModelsResponseItem = zod.object({
  "id": zod.number(),
  "brand_id": zod.number(),
  "name": zod.string(),
  "listing_count": zod.number().nullish()
})
export const ListBrandModelsResponse = zod.array(ListBrandModelsResponseItem)


/**
 * @summary List vehicle types
 */
export const ListVehicleTypesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string(),
  "icon": zod.string().nullish(),
  "listing_count": zod.number().nullish()
})
export const ListVehicleTypesResponse = zod.array(ListVehicleTypesResponseItem)


/**
 * @summary List fuel types
 */
export const ListFuelTypesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string()
})
export const ListFuelTypesResponse = zod.array(ListFuelTypesResponseItem)


/**
 * @summary List transmissions
 */
export const ListTransmissionsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string()
})
export const ListTransmissionsResponse = zod.array(ListTransmissionsResponseItem)


/**
 * @summary List conditions
 */
export const ListConditionsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string()
})
export const ListConditionsResponse = zod.array(ListConditionsResponseItem)


/**
 * @summary List colors
 */
export const ListColorsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string(),
  "hex_code": zod.string().nullish()
})
export const ListColorsResponse = zod.array(ListColorsResponseItem)


/**
 * @summary List regions
 */
export const listRegionsQueryWithCountsDefault = false;

export const ListRegionsQueryParams = zod.object({
  "with_counts": zod.coerce.boolean().default(listRegionsQueryWithCountsDefault)
})

export const ListRegionsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string(),
  "listing_count": zod.number().nullish()
})
export const ListRegionsResponse = zod.array(ListRegionsResponseItem)


/**
 * @summary List cities in a region
 */
export const ListRegionCitiesParams = zod.object({
  "id": zod.coerce.number()
})

export const ListRegionCitiesResponseItem = zod.object({
  "id": zod.number(),
  "region_id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string(),
  "listing_count": zod.number().nullish()
})
export const ListRegionCitiesResponse = zod.array(ListRegionCitiesResponseItem)


/**
 * @summary List all cities
 */
export const listCitiesQueryWithCountsDefault = false;

export const ListCitiesQueryParams = zod.object({
  "with_counts": zod.coerce.boolean().default(listCitiesQueryWithCountsDefault)
})

export const ListCitiesResponseItem = zod.object({
  "id": zod.number(),
  "region_id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "name_ku": zod.string(),
  "listing_count": zod.number().nullish()
})
export const ListCitiesResponse = zod.array(ListCitiesResponseItem)


/**
 * @summary Get current IQD/USD exchange rate
 */
export const GetExchangeRatesResponse = zod.object({
  "iqd_per_usd": zod.number(),
  "updated_at": zod.string()
})


/**
 * @summary Get current user's favorites
 */
export const ListFavoritesResponseItem = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand": zod.string(),
  "model": zod.string(),
  "year": zod.number(),
  "price": zod.number(),
  "price_usd": zod.number().nullish(),
  "currency": zod.string(),
  "mileage": zod.number().nullish(),
  "condition": zod.string(),
  "city": zod.string(),
  "region": zod.string(),
  "cover_image": zod.string().nullish(),
  "is_negotiable": zod.boolean(),
  "is_featured": zod.boolean(),
  "seller_type": zod.string(),
  "views_count": zod.number(),
  "favorites_count": zod.number(),
  "is_favorited": zod.boolean().nullish(),
  "status": zod.string(),
  "created_at": zod.string()
})
export const ListFavoritesResponse = zod.array(ListFavoritesResponseItem)


/**
 * @summary Add vehicle to favorites
 */
export const AddFavoriteParams = zod.object({
  "vehicleId": zod.coerce.string()
})

export const AddFavoriteResponse = zod.object({
  "vehicle_id": zod.string(),
  "is_favorited": zod.boolean()
})


/**
 * @summary Remove vehicle from favorites
 */
export const RemoveFavoriteParams = zod.object({
  "vehicleId": zod.coerce.string()
})

export const RemoveFavoriteResponse = zod.object({
  "vehicle_id": zod.string(),
  "is_favorited": zod.boolean()
})


/**
 * @summary Get current user profile
 */
export const GetProfileResponse = zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "display_name": zod.string(),
  "avatar_url": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "city_id": zod.number().nullish(),
  "region_id": zod.number().nullish(),
  "role": zod.string(),
  "is_dealer": zod.boolean(),
  "created_at": zod.string()
})


/**
 * @summary Update current user profile
 */
export const UpdateProfileBody = zod.object({
  "display_name": zod.string().nullish(),
  "avatar_url": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "city_id": zod.number().nullish(),
  "region_id": zod.number().nullish()
})

export const UpdateProfileResponse = zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "display_name": zod.string(),
  "avatar_url": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "city_id": zod.number().nullish(),
  "region_id": zod.number().nullish(),
  "role": zod.string(),
  "is_dealer": zod.boolean(),
  "created_at": zod.string()
})


/**
 * @summary Get current user's vehicle listings
 */
export const GetMyVehiclesQueryParams = zod.object({
  "status": zod.union([zod.literal('draft'),zod.literal('active'),zod.literal('sold'),zod.literal('deleted'),zod.literal(null)]).nullish()
})

export const GetMyVehiclesResponseItem = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand": zod.string(),
  "model": zod.string(),
  "year": zod.number(),
  "price": zod.number(),
  "price_usd": zod.number().nullish(),
  "currency": zod.string(),
  "mileage": zod.number().nullish(),
  "condition": zod.string(),
  "city": zod.string(),
  "region": zod.string(),
  "cover_image": zod.string().nullish(),
  "is_negotiable": zod.boolean(),
  "is_featured": zod.boolean(),
  "seller_type": zod.string(),
  "views_count": zod.number(),
  "favorites_count": zod.number(),
  "is_favorited": zod.boolean().nullish(),
  "status": zod.string(),
  "created_at": zod.string()
})
export const GetMyVehiclesResponse = zod.array(GetMyVehiclesResponseItem)


/**
 * @summary List verified dealers
 */
export const listDealersQueryLimitDefault = 20;

export const ListDealersQueryParams = zod.object({
  "city_id": zod.coerce.number().nullish(),
  "limit": zod.coerce.number().default(listDealersQueryLimitDefault)
})

export const ListDealersResponseItem = zod.object({
  "id": zod.string(),
  "business_name": zod.string(),
  "logo_url": zod.string().nullish(),
  "city": zod.string(),
  "is_verified": zod.boolean(),
  "listing_count": zod.number().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish()
})
export const ListDealersResponse = zod.array(ListDealersResponseItem)


/**
 * @summary Get dealer profile
 */
export const GetDealerParams = zod.object({
  "id": zod.coerce.string()
})

export const GetDealerResponse = zod.object({
  "id": zod.string(),
  "user_id": zod.string(),
  "business_name": zod.string(),
  "logo_url": zod.string().nullish(),
  "banner_url": zod.string().nullish(),
  "description": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "website": zod.string().nullish(),
  "facebook": zod.string().nullish(),
  "instagram": zod.string().nullish(),
  "city_id": zod.number(),
  "region_id": zod.number(),
  "city": zod.string(),
  "region": zod.string(),
  "latitude": zod.number().nullish(),
  "longitude": zod.number().nullish(),
  "is_verified": zod.boolean(),
  "listing_count": zod.number(),
  "created_at": zod.string()
})


/**
 * @summary Get dealer's active listings
 */
export const GetDealerVehiclesParams = zod.object({
  "id": zod.coerce.string()
})

export const GetDealerVehiclesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand": zod.string(),
  "model": zod.string(),
  "year": zod.number(),
  "price": zod.number(),
  "price_usd": zod.number().nullish(),
  "currency": zod.string(),
  "mileage": zod.number().nullish(),
  "condition": zod.string(),
  "city": zod.string(),
  "region": zod.string(),
  "cover_image": zod.string().nullish(),
  "is_negotiable": zod.boolean(),
  "is_featured": zod.boolean(),
  "seller_type": zod.string(),
  "views_count": zod.number(),
  "favorites_count": zod.number(),
  "is_favorited": zod.boolean().nullish(),
  "status": zod.string(),
  "created_at": zod.string()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number(),
  "total_pages": zod.number()
})


/**
 * @summary Get current user's dealer profile
 */
export const GetMyDealerProfileResponse = zod.object({
  "id": zod.string(),
  "user_id": zod.string(),
  "business_name": zod.string(),
  "logo_url": zod.string().nullish(),
  "banner_url": zod.string().nullish(),
  "description": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "website": zod.string().nullish(),
  "facebook": zod.string().nullish(),
  "instagram": zod.string().nullish(),
  "city_id": zod.number(),
  "region_id": zod.number(),
  "city": zod.string(),
  "region": zod.string(),
  "latitude": zod.number().nullish(),
  "longitude": zod.number().nullish(),
  "is_verified": zod.boolean(),
  "listing_count": zod.number(),
  "created_at": zod.string()
})


/**
 * @summary Create dealer profile for current user
 */
export const CreateDealerProfileBody = zod.object({
  "business_name": zod.string(),
  "logo_url": zod.string().nullish(),
  "banner_url": zod.string().nullish(),
  "description": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "website": zod.string().nullish(),
  "facebook": zod.string().nullish(),
  "instagram": zod.string().nullish(),
  "city_id": zod.number(),
  "region_id": zod.number(),
  "latitude": zod.number().nullish(),
  "longitude": zod.number().nullish()
})

export const CreateDealerProfileResponse = zod.object({
  "id": zod.string(),
  "user_id": zod.string(),
  "business_name": zod.string(),
  "logo_url": zod.string().nullish(),
  "banner_url": zod.string().nullish(),
  "description": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "website": zod.string().nullish(),
  "facebook": zod.string().nullish(),
  "instagram": zod.string().nullish(),
  "city_id": zod.number(),
  "region_id": zod.number(),
  "city": zod.string(),
  "region": zod.string(),
  "latitude": zod.number().nullish(),
  "longitude": zod.number().nullish(),
  "is_verified": zod.boolean(),
  "listing_count": zod.number(),
  "created_at": zod.string()
})


/**
 * @summary Update current user's dealer profile
 */
export const UpdateDealerProfileBody = zod.object({
  "business_name": zod.string().nullish(),
  "logo_url": zod.string().nullish(),
  "banner_url": zod.string().nullish(),
  "description": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "website": zod.string().nullish(),
  "facebook": zod.string().nullish(),
  "instagram": zod.string().nullish()
})

export const UpdateDealerProfileResponse = zod.object({
  "id": zod.string(),
  "user_id": zod.string(),
  "business_name": zod.string(),
  "logo_url": zod.string().nullish(),
  "banner_url": zod.string().nullish(),
  "description": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "website": zod.string().nullish(),
  "facebook": zod.string().nullish(),
  "instagram": zod.string().nullish(),
  "city_id": zod.number(),
  "region_id": zod.number(),
  "city": zod.string(),
  "region": zod.string(),
  "latitude": zod.number().nullish(),
  "longitude": zod.number().nullish(),
  "is_verified": zod.boolean(),
  "listing_count": zod.number(),
  "created_at": zod.string()
})


/**
 * @summary List user's conversations
 */
export const ListConversationsResponseItem = zod.object({
  "vehicle_id": zod.string(),
  "vehicle_title": zod.string(),
  "vehicle_cover": zod.string().nullish(),
  "other_user": zod.object({
  "id": zod.string(),
  "display_name": zod.string(),
  "avatar_url": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "role": zod.string(),
  "created_at": zod.string()
}),
  "last_message": zod.string(),
  "last_message_at": zod.string(),
  "unread_count": zod.number()
})
export const ListConversationsResponse = zod.array(ListConversationsResponseItem)


/**
 * @summary Get messages for a vehicle conversation
 */
export const GetConversationParams = zod.object({
  "vehicleId": zod.coerce.string()
})

export const GetConversationResponseItem = zod.object({
  "id": zod.string(),
  "vehicle_id": zod.string(),
  "sender_id": zod.string(),
  "receiver_id": zod.string(),
  "content": zod.string(),
  "is_read": zod.boolean(),
  "created_at": zod.string(),
  "sender": zod.object({
  "id": zod.string(),
  "display_name": zod.string(),
  "avatar_url": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "role": zod.string(),
  "created_at": zod.string()
})
})
export const GetConversationResponse = zod.array(GetConversationResponseItem)


/**
 * @summary Send a message about a vehicle
 */
export const SendMessageParams = zod.object({
  "vehicleId": zod.coerce.string()
})

export const SendMessageBody = zod.object({
  "content": zod.string(),
  "receiver_id": zod.string()
})

export const SendMessageResponse = zod.object({
  "id": zod.string(),
  "vehicle_id": zod.string(),
  "sender_id": zod.string(),
  "receiver_id": zod.string(),
  "content": zod.string(),
  "is_read": zod.boolean(),
  "created_at": zod.string(),
  "sender": zod.object({
  "id": zod.string(),
  "display_name": zod.string(),
  "avatar_url": zod.string().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish(),
  "role": zod.string(),
  "created_at": zod.string()
})
})


/**
 * @summary Get marketplace stats for the landing page
 */
export const GetDashboardStatsResponse = zod.object({
  "total_listings": zod.number(),
  "active_listings": zod.number(),
  "total_users": zod.number(),
  "total_dealers": zod.number(),
  "today_listings": zod.number()
})


/**
 * @summary Get popular brands with listing counts
 */
export const getPopularBrandsQueryLimitDefault = 10;

export const GetPopularBrandsQueryParams = zod.object({
  "limit": zod.coerce.number().default(getPopularBrandsQueryLimitDefault)
})

export const GetPopularBrandsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "logo_url": zod.string().nullish(),
  "listing_count": zod.number()
})
export const GetPopularBrandsResponse = zod.array(GetPopularBrandsResponseItem)


/**
 * @summary Get popular cities with listing counts
 */
export const getPopularCitiesQueryLimitDefault = 8;

export const GetPopularCitiesQueryParams = zod.object({
  "limit": zod.coerce.number().default(getPopularCitiesQueryLimitDefault)
})

export const GetPopularCitiesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "name_ar": zod.string(),
  "listing_count": zod.number()
})
export const GetPopularCitiesResponse = zod.array(GetPopularCitiesResponseItem)


/**
 * @summary Admin overview statistics
 */
export const GetAdminStatsResponse = zod.object({
  "total_users": zod.number(),
  "total_dealers": zod.number(),
  "total_listings": zod.number(),
  "active_listings": zod.number(),
  "pending_listings": zod.number(),
  "total_reports": zod.number(),
  "pending_reports": zod.number(),
  "today_signups": zod.number(),
  "today_listings": zod.number()
})


/**
 * @summary Admin list all vehicles
 */
export const adminListVehiclesQueryPageDefault = 1;

export const AdminListVehiclesQueryParams = zod.object({
  "page": zod.coerce.number().default(adminListVehiclesQueryPageDefault),
  "status": zod.coerce.string().nullish(),
  "keyword": zod.coerce.string().nullish()
})

export const AdminListVehiclesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "brand": zod.string(),
  "model": zod.string(),
  "year": zod.number(),
  "price": zod.number(),
  "price_usd": zod.number().nullish(),
  "currency": zod.string(),
  "mileage": zod.number().nullish(),
  "condition": zod.string(),
  "city": zod.string(),
  "region": zod.string(),
  "cover_image": zod.string().nullish(),
  "is_negotiable": zod.boolean(),
  "is_featured": zod.boolean(),
  "seller_type": zod.string(),
  "views_count": zod.number(),
  "favorites_count": zod.number(),
  "is_favorited": zod.boolean().nullish(),
  "status": zod.string(),
  "created_at": zod.string()
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number(),
  "total_pages": zod.number()
})


/**
 * @summary Approve a vehicle listing
 */
export const AdminApproveVehicleParams = zod.object({
  "id": zod.coerce.string()
})

export const AdminApproveVehicleResponse = zod.unknown()


/**
 * @summary Reject a vehicle listing
 */
export const AdminRejectVehicleParams = zod.object({
  "id": zod.coerce.string()
})

export const AdminRejectVehicleBody = zod.object({
  "reason": zod.string()
})

export const AdminRejectVehicleResponse = zod.unknown()


/**
 * @summary Admin list all users
 */
export const adminListUsersQueryPageDefault = 1;

export const AdminListUsersQueryParams = zod.object({
  "page": zod.coerce.number().default(adminListUsersQueryPageDefault),
  "keyword": zod.coerce.string().nullish(),
  "role": zod.coerce.string().nullish()
})

export const AdminListUsersResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "display_name": zod.string(),
  "role": zod.string(),
  "is_dealer": zod.boolean(),
  "listing_count": zod.number(),
  "created_at": zod.string()
})),
  "total": zod.number(),
  "page": zod.number()
})


/**
 * @summary Admin list all dealers
 */
export const adminListDealersQueryPageDefault = 1;

export const AdminListDealersQueryParams = zod.object({
  "page": zod.coerce.number().default(adminListDealersQueryPageDefault),
  "verified": zod.coerce.boolean().nullish()
})

export const AdminListDealersResponseItem = zod.object({
  "id": zod.string(),
  "business_name": zod.string(),
  "logo_url": zod.string().nullish(),
  "city": zod.string(),
  "is_verified": zod.boolean(),
  "listing_count": zod.number().nullish(),
  "phone": zod.string().nullish(),
  "whatsapp": zod.string().nullish()
})
export const AdminListDealersResponse = zod.array(AdminListDealersResponseItem)


/**
 * @summary Verify a dealer
 */
export const AdminVerifyDealerParams = zod.object({
  "id": zod.coerce.string()
})

export const AdminVerifyDealerResponse = zod.unknown()


/**
 * @summary Admin list brands
 */
export const AdminListBrandsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "logo_url": zod.string().nullish(),
  "listing_count": zod.number().nullish()
})
export const AdminListBrandsResponse = zod.array(AdminListBrandsResponseItem)


/**
 * @summary Create a brand
 */
export const AdminCreateBrandBody = zod.object({
  "name": zod.string(),
  "logo_url": zod.string().nullish()
})

export const AdminCreateBrandResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "logo_url": zod.string().nullish(),
  "listing_count": zod.number().nullish()
})


/**
 * @summary Update the IQD/USD exchange rate
 */
export const AdminUpdateExchangeRateBody = zod.object({
  "iqd_per_usd": zod.number()
})

export const AdminUpdateExchangeRateResponse = zod.object({
  "iqd_per_usd": zod.number(),
  "updated_at": zod.string()
})


/**
 * @summary Feature a vehicle listing
 */
export const AdminFeatureVehicleParams = zod.object({
  "vehicleId": zod.coerce.string()
})

export const AdminFeatureVehicleBody = zod.object({
  "expires_at": zod.string().nullish()
})

export const AdminFeatureVehicleResponse = zod.unknown()


/**
 * @summary Remove featured status
 */
export const AdminUnfeatureVehicleParams = zod.object({
  "vehicleId": zod.coerce.string()
})

export const AdminUnfeatureVehicleResponse = zod.void()


/**
 * @summary Get pending reports
 */
export const adminListReportsQueryPageDefault = 1;

export const AdminListReportsQueryParams = zod.object({
  "page": zod.coerce.number().default(adminListReportsQueryPageDefault),
  "status": zod.coerce.string().nullish()
})

export const AdminListReportsResponseItem = zod.object({
  "id": zod.string(),
  "vehicle_id": zod.string(),
  "vehicle_title": zod.string(),
  "reporter_id": zod.string(),
  "reason": zod.string(),
  "description": zod.string().nullish(),
  "status": zod.string(),
  "created_at": zod.string()
})
export const AdminListReportsResponse = zod.array(AdminListReportsResponseItem)


