/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface VehicleType {
  id: number;
  name: string;
  name_ar: string;
  name_ku: string;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  listing_count?: number | null;
}

export interface FuelType {
  id: number;
  name: string;
  name_ar: string;
  name_ku: string;
}

export interface Transmission {
  id: number;
  name: string;
  name_ar: string;
  name_ku: string;
}

export interface Condition {
  id: number;
  name: string;
  name_ar: string;
  name_ku: string;
}

export interface VehicleColor {
  id: number;
  name: string;
  name_ar: string;
  name_ku: string;
  /** @nullable */
  hex_code?: string | null;
}

export interface Brand {
  id: number;
  name: string;
  /** @nullable */
  logo_url?: string | null;
  /** @nullable */
  listing_count?: number | null;
}

export interface BrandInput {
  name: string;
  /** @nullable */
  logo_url?: string | null;
}

export interface VehicleModel {
  id: number;
  brand_id: number;
  name: string;
  /** @nullable */
  listing_count?: number | null;
}

export interface Region {
  id: number;
  name: string;
  name_ar: string;
  name_ku: string;
  /** @nullable */
  listing_count?: number | null;
}

export interface City {
  id: number;
  region_id: number;
  name: string;
  name_ar: string;
  name_ku: string;
  /** @nullable */
  listing_count?: number | null;
}

export interface ExchangeRate {
  iqd_per_usd: number;
  updated_at: string;
}

export interface ExchangeRateUpdate {
  iqd_per_usd: number;
}

export interface VehicleImage {
  id: string;
  url: string;
  /** @nullable */
  thumbnail_url?: string | null;
  is_cover: boolean;
  sort_order: number;
}

export interface VehicleImageInput {
  url: string;
  /** @nullable */
  thumbnail_url?: string | null;
  is_cover?: boolean;
  sort_order?: number;
}

export interface VehicleSummary {
  id: string;
  title: string;
  brand: string;
  model: string;
  year: number;
  price: number;
  /** @nullable */
  price_usd?: number | null;
  currency: string;
  /** @nullable */
  mileage?: number | null;
  condition: string;
  city: string;
  region: string;
  /** @nullable */
  cover_image?: string | null;
  is_negotiable: boolean;
  is_featured: boolean;
  seller_type: string;
  views_count: number;
  favorites_count: number;
  /** @nullable */
  is_favorited?: boolean | null;
  status: string;
  created_at: string;
}

export interface Vehicle {
  id: string;
  title: string;
  brand_id: number;
  model_id: number;
  vehicle_type_id: number;
  year: number;
  /** @nullable */
  mileage?: number | null;
  /** @nullable */
  engine_size?: number | null;
  /** @nullable */
  horsepower?: number | null;
  /** @nullable */
  transmission_id?: number | null;
  /** @nullable */
  fuel_type_id?: number | null;
  /** @nullable */
  drive_type_id?: number | null;
  /** @nullable */
  color_id?: number | null;
  condition_id: number;
  /** @nullable */
  vin?: string | null;
  price: number;
  currency: string;
  is_negotiable: boolean;
  /** @nullable */
  description?: string | null;
  region_id: number;
  city_id: number;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  status: string;
  owner_id: string;
  /** @nullable */
  dealer_id?: string | null;
  created_at: string;
  updated_at: string;
}

export interface PublicUser {
  id: string;
  display_name: string;
  /** @nullable */
  avatar_url?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  whatsapp?: string | null;
  role: string;
  created_at: string;
}

export interface DealerSummary {
  id: string;
  business_name: string;
  /** @nullable */
  logo_url?: string | null;
  city: string;
  is_verified: boolean;
  /** @nullable */
  listing_count?: number | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  whatsapp?: string | null;
}

export interface VehicleDetail {
  id: string;
  title: string;
  brand: Brand;
  model: VehicleModel;
  vehicle_type: VehicleType;
  year: number;
  /** @nullable */
  mileage?: number | null;
  /** @nullable */
  engine_size?: number | null;
  /** @nullable */
  horsepower?: number | null;
  transmission?: Transmission;
  fuel_type?: FuelType;
  color?: VehicleColor;
  condition: Condition;
  /** @nullable */
  vin?: string | null;
  price: number;
  /** @nullable */
  price_usd?: number | null;
  /** @nullable */
  price_iqd?: number | null;
  currency: string;
  is_negotiable: boolean;
  /** @nullable */
  description?: string | null;
  region: Region;
  city: City;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  images: VehicleImage[];
  seller: PublicUser;
  dealer?: DealerSummary;
  is_featured: boolean;
  /** @nullable */
  is_favorited?: boolean | null;
  views_count: number;
  favorites_count: number;
  status: string;
  created_at: string;
  updated_at: string;
}

export type VehicleInputCurrency = typeof VehicleInputCurrency[keyof typeof VehicleInputCurrency];


export const VehicleInputCurrency = {
  USD: 'USD',
  IQD: 'IQD',
} as const;

export type VehicleInputStatus = typeof VehicleInputStatus[keyof typeof VehicleInputStatus];


export const VehicleInputStatus = {
  draft: 'draft',
  active: 'active',
} as const;

export interface VehicleInput {
  title: string;
  brand_id: number;
  model_id: number;
  vehicle_type_id: number;
  year: number;
  /** @nullable */
  mileage?: number | null;
  /** @nullable */
  engine_size?: number | null;
  /** @nullable */
  horsepower?: number | null;
  /** @nullable */
  transmission_id?: number | null;
  /** @nullable */
  fuel_type_id?: number | null;
  /** @nullable */
  color_id?: number | null;
  condition_id: number;
  /** @nullable */
  vin?: string | null;
  price: number;
  currency: VehicleInputCurrency;
  is_negotiable?: boolean;
  /** @nullable */
  description?: string | null;
  region_id: number;
  city_id: number;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  status?: VehicleInputStatus;
}

export interface VehicleUpdate {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  price?: number | null;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  is_negotiable?: boolean | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  mileage?: number | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  city_id?: number | null;
  /** @nullable */
  region_id?: number | null;
}

export interface VehicleListResponse {
  data: VehicleSummary[];
  total: number;
  page: number;
  limit: number;
  total_pages: number;
}

export interface UserProfile {
  id: string;
  email: string;
  display_name: string;
  /** @nullable */
  avatar_url?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  whatsapp?: string | null;
  /** @nullable */
  city_id?: number | null;
  /** @nullable */
  region_id?: number | null;
  role: string;
  is_dealer: boolean;
  created_at: string;
}

export interface ProfileUpdate {
  /** @nullable */
  display_name?: string | null;
  /** @nullable */
  avatar_url?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  whatsapp?: string | null;
  /** @nullable */
  city_id?: number | null;
  /** @nullable */
  region_id?: number | null;
}

export interface DealerProfile {
  id: string;
  user_id: string;
  business_name: string;
  /** @nullable */
  logo_url?: string | null;
  /** @nullable */
  banner_url?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  whatsapp?: string | null;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  facebook?: string | null;
  /** @nullable */
  instagram?: string | null;
  city_id: number;
  region_id: number;
  city: string;
  region: string;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  is_verified: boolean;
  listing_count: number;
  created_at: string;
}

export interface DealerInput {
  business_name: string;
  /** @nullable */
  logo_url?: string | null;
  /** @nullable */
  banner_url?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  whatsapp?: string | null;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  facebook?: string | null;
  /** @nullable */
  instagram?: string | null;
  city_id: number;
  region_id: number;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
}

export interface DealerUpdate {
  /** @nullable */
  business_name?: string | null;
  /** @nullable */
  logo_url?: string | null;
  /** @nullable */
  banner_url?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  whatsapp?: string | null;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  facebook?: string | null;
  /** @nullable */
  instagram?: string | null;
}

export interface FavoriteStatus {
  vehicle_id: string;
  is_favorited: boolean;
}

export interface Message {
  id: string;
  vehicle_id: string;
  sender_id: string;
  receiver_id: string;
  content: string;
  is_read: boolean;
  created_at: string;
  sender: PublicUser;
}

export interface MessageInput {
  content: string;
  receiver_id: string;
}

export interface Conversation {
  vehicle_id: string;
  vehicle_title: string;
  /** @nullable */
  vehicle_cover?: string | null;
  other_user: PublicUser;
  last_message: string;
  last_message_at: string;
  unread_count: number;
}

export type ReportInputReason = typeof ReportInputReason[keyof typeof ReportInputReason];


export const ReportInputReason = {
  spam: 'spam',
  fraud: 'fraud',
  inappropriate: 'inappropriate',
  duplicate: 'duplicate',
  other: 'other',
} as const;

export interface ReportInput {
  reason: ReportInputReason;
  /** @nullable */
  description?: string | null;
}

export interface VehicleReport {
  id: string;
  vehicle_id: string;
  vehicle_title: string;
  reporter_id: string;
  reason: string;
  /** @nullable */
  description?: string | null;
  status: string;
  created_at: string;
}

export interface RejectInput {
  reason: string;
}

export interface DashboardStats {
  total_listings: number;
  active_listings: number;
  total_users: number;
  total_dealers: number;
  today_listings: number;
}

export interface BrandStat {
  id: number;
  name: string;
  /** @nullable */
  logo_url?: string | null;
  listing_count: number;
}

export interface CityStat {
  id: number;
  name: string;
  name_ar: string;
  listing_count: number;
}

export interface AdminStats {
  total_users: number;
  total_dealers: number;
  total_listings: number;
  active_listings: number;
  pending_listings: number;
  total_reports: number;
  pending_reports: number;
  today_signups: number;
  today_listings: number;
}

export interface AdminUser {
  id: string;
  email: string;
  display_name: string;
  role: string;
  is_dealer: boolean;
  listing_count: number;
  created_at: string;
}

export interface AdminUserListResponse {
  data: AdminUser[];
  total: number;
  page: number;
}

export interface FeaturedInput {
  /** @nullable */
  expires_at?: string | null;
}

export type ListVehiclesParams = {
page?: number;
limit?: number;
/**
 * @nullable
 */
brand_id?: number | null;
/**
 * @nullable
 */
model_id?: number | null;
/**
 * @nullable
 */
vehicle_type_id?: number | null;
/**
 * @nullable
 */
condition_id?: number | null;
/**
 * @nullable
 */
fuel_type_id?: number | null;
/**
 * @nullable
 */
transmission_id?: number | null;
/**
 * @nullable
 */
region_id?: number | null;
/**
 * @nullable
 */
city_id?: number | null;
/**
 * @nullable
 */
year_min?: number | null;
/**
 * @nullable
 */
year_max?: number | null;
/**
 * @nullable
 */
price_min?: number | null;
/**
 * @nullable
 */
price_max?: number | null;
/**
 * @nullable
 */
mileage_max?: number | null;
/**
 * @nullable
 */
color_id?: number | null;
/**
 * @nullable
 */
seller_type?: ListVehiclesSellerType;
/**
 * @nullable
 */
is_negotiable?: boolean | null;
/**
 * @nullable
 */
keyword?: string | null;
sort?: ListVehiclesSort;
/**
 * @nullable
 */
featured_only?: boolean | null;
currency?: string;
};

export type ListVehiclesSellerType = typeof ListVehiclesSellerType[keyof typeof ListVehiclesSellerType] | null;


export const ListVehiclesSellerType = {
  individual: 'individual',
  dealer: 'dealer',
} as const;

export type ListVehiclesSort = typeof ListVehiclesSort[keyof typeof ListVehiclesSort];


export const ListVehiclesSort = {
  newest: 'newest',
  oldest: 'oldest',
  price_asc: 'price_asc',
  price_desc: 'price_desc',
  most_viewed: 'most_viewed',
  most_favorited: 'most_favorited',
} as const;

export type ListFeaturedVehiclesParams = {
limit?: number;
};

export type ListLatestVehiclesParams = {
limit?: number;
};

export type ListBrandsParams = {
/**
 * @nullable
 */
vehicle_type_id?: number | null;
with_counts?: boolean;
};

export type ListRegionsParams = {
with_counts?: boolean;
};

export type ListCitiesParams = {
with_counts?: boolean;
};

export type GetMyVehiclesParams = {
/**
 * @nullable
 */
status?: GetMyVehiclesStatus;
};

export type GetMyVehiclesStatus = typeof GetMyVehiclesStatus[keyof typeof GetMyVehiclesStatus] | null;


export const GetMyVehiclesStatus = {
  draft: 'draft',
  active: 'active',
  sold: 'sold',
  deleted: 'deleted',
} as const;

export type ListDealersParams = {
/**
 * @nullable
 */
city_id?: number | null;
limit?: number;
};

export type GetPopularBrandsParams = {
limit?: number;
};

export type GetPopularCitiesParams = {
limit?: number;
};

export type AdminListVehiclesParams = {
page?: number;
/**
 * @nullable
 */
status?: string | null;
/**
 * @nullable
 */
keyword?: string | null;
};

export type AdminListUsersParams = {
page?: number;
/**
 * @nullable
 */
keyword?: string | null;
/**
 * @nullable
 */
role?: string | null;
};

export type AdminListDealersParams = {
page?: number;
/**
 * @nullable
 */
verified?: boolean | null;
};

export type AdminListReportsParams = {
page?: number;
/**
 * @nullable
 */
status?: string | null;
};

