/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export interface Brand {
  id: number;
  name: string;
  /** @nullable */
  logo_url?: string | null;
  /** @nullable */
  listing_count?: number | null;
}
