/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { PublicUser } from './publicUser';

export interface Conversation {
  vehicle_id: string;
  vehicle_title: string;
  /** @nullable */
  vehicle_cover?: string | null;
  other_user: PublicUser;
  last_message: string;
  last_message_at: string;
  unread_count: number;
}
