/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardStats {
  total_listings: number;
  active_listings: number;
  total_users: number;
  total_dealers: number;
  today_listings: number;
}
