/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export interface DealerSummary {
  id: string;
  business_name: string;
  /** @nullable */
  logo_url?: string | null;
  city: string;
  is_verified: boolean;
  /** @nullable */
  listing_count?: number | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  whatsapp?: string | null;
}
