/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export interface DealerProfile {
  id: string;
  user_id: string;
  business_name: string;
  /** @nullable */
  logo_url?: string | null;
  /** @nullable */
  banner_url?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  whatsapp?: string | null;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  facebook?: string | null;
  /** @nullable */
  instagram?: string | null;
  city_id: number;
  region_id: number;
  city: string;
  region: string;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  is_verified: boolean;
  listing_count: number;
  created_at: string;
}
