/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { ListVehiclesSellerType } from './listVehiclesSellerType';
import type { ListVehiclesSort } from './listVehiclesSort';

export type ListVehiclesParams = {
page?: number;
limit?: number;
/**
 * @nullable
 */
brand_id?: number | null;
/**
 * @nullable
 */
model_id?: number | null;
/**
 * @nullable
 */
vehicle_type_id?: number | null;
/**
 * @nullable
 */
condition_id?: number | null;
/**
 * @nullable
 */
fuel_type_id?: number | null;
/**
 * @nullable
 */
transmission_id?: number | null;
/**
 * @nullable
 */
region_id?: number | null;
/**
 * @nullable
 */
city_id?: number | null;
/**
 * @nullable
 */
year_min?: number | null;
/**
 * @nullable
 */
year_max?: number | null;
/**
 * @nullable
 */
price_min?: number | null;
/**
 * @nullable
 */
price_max?: number | null;
/**
 * @nullable
 */
mileage_max?: number | null;
/**
 * @nullable
 */
color_id?: number | null;
/**
 * @nullable
 */
seller_type?: ListVehiclesSellerType;
/**
 * @nullable
 */
is_negotiable?: boolean | null;
/**
 * @nullable
 */
keyword?: string | null;
sort?: ListVehiclesSort;
/**
 * @nullable
 */
featured_only?: boolean | null;
currency?: string;
};
