/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export type ListBrandsParams = {
/**
 * @nullable
 */
vehicle_type_id?: number | null;
with_counts?: boolean;
};
