/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export type ListVehiclesSellerType = typeof ListVehiclesSellerType[keyof typeof ListVehiclesSellerType] | null;


export const ListVehiclesSellerType = {
  individual: 'individual',
  dealer: 'dealer',
} as const;
