/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export type ListVehiclesSort = typeof ListVehiclesSort[keyof typeof ListVehiclesSort];


export const ListVehiclesSort = {
  newest: 'newest',
  oldest: 'oldest',
  price_asc: 'price_asc',
  price_desc: 'price_desc',
  most_viewed: 'most_viewed',
  most_favorited: 'most_favorited',
} as const;
