/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export interface ProfileUpdate {
  /** @nullable */
  display_name?: string | null;
  /** @nullable */
  avatar_url?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  whatsapp?: string | null;
  /** @nullable */
  city_id?: number | null;
  /** @nullable */
  region_id?: number | null;
}
