/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { ReportInputReason } from './reportInputReason';

export interface ReportInput {
  reason: ReportInputReason;
  /** @nullable */
  description?: string | null;
}
