/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export type ReportInputReason = typeof ReportInputReason[keyof typeof ReportInputReason];


export const ReportInputReason = {
  spam: 'spam',
  fraud: 'fraud',
  inappropriate: 'inappropriate',
  duplicate: 'duplicate',
  other: 'other',
} as const;
