/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { Brand } from './brand';
import type { City } from './city';
import type { Condition } from './condition';
import type { DealerSummary } from './dealerSummary';
import type { FuelType } from './fuelType';
import type { PublicUser } from './publicUser';
import type { Region } from './region';
import type { Transmission } from './transmission';
import type { VehicleColor } from './vehicleColor';
import type { VehicleImage } from './vehicleImage';
import type { VehicleModel } from './vehicleModel';
import type { VehicleType } from './vehicleType';

export interface VehicleDetail {
  id: string;
  title: string;
  brand: Brand;
  model: VehicleModel;
  vehicle_type: VehicleType;
  year: number;
  /** @nullable */
  mileage?: number | null;
  /** @nullable */
  engine_size?: number | null;
  /** @nullable */
  horsepower?: number | null;
  transmission?: Transmission;
  fuel_type?: FuelType;
  color?: VehicleColor;
  condition: Condition;
  /** @nullable */
  vin?: string | null;
  price: number;
  /** @nullable */
  price_usd?: number | null;
  /** @nullable */
  price_iqd?: number | null;
  currency: string;
  is_negotiable: boolean;
  /** @nullable */
  description?: string | null;
  region: Region;
  city: City;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  images: VehicleImage[];
  seller: PublicUser;
  dealer?: DealerSummary;
  is_featured: boolean;
  /** @nullable */
  is_favorited?: boolean | null;
  views_count: number;
  favorites_count: number;
  status: string;
  created_at: string;
  updated_at: string;
}
