/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export interface VehicleImage {
  id: string;
  url: string;
  /** @nullable */
  thumbnail_url?: string | null;
  is_cover: boolean;
  sort_order: number;
}
