/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export type VehicleInputCurrency = typeof VehicleInputCurrency[keyof typeof VehicleInputCurrency];


export const VehicleInputCurrency = {
  USD: 'USD',
  IQD: 'IQD',
} as const;
