/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export interface VehicleSummary {
  id: string;
  title: string;
  brand: string;
  model: string;
  year: number;
  price: number;
  /** @nullable */
  price_usd?: number | null;
  currency: string;
  /** @nullable */
  mileage?: number | null;
  condition: string;
  city: string;
  region: string;
  /** @nullable */
  cover_image?: string | null;
  is_negotiable: boolean;
  is_featured: boolean;
  seller_type: string;
  views_count: number;
  favorites_count: number;
  /** @nullable */
  is_favorited?: boolean | null;
  status: string;
  created_at: string;
}
