/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export interface VehicleReport {
  id: string;
  vehicle_id: string;
  vehicle_title: string;
  reporter_id: string;
  reason: string;
  /** @nullable */
  description?: string | null;
  status: string;
  created_at: string;
}
