/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */

export interface VehicleUpdate {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  price?: number | null;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  is_negotiable?: boolean | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  mileage?: number | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  city_id?: number | null;
  /** @nullable */
  region_id?: number | null;
}
