/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * IQ Motor - Motorcycle & Bike Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { VehicleInputCurrency } from './vehicleInputCurrency';
import type { VehicleInputStatus } from './vehicleInputStatus';

export interface VehicleInput {
  title: string;
  brand_id: number;
  model_id: number;
  vehicle_type_id: number;
  year: number;
  /** @nullable */
  mileage?: number | null;
  /** @nullable */
  engine_size?: number | null;
  /** @nullable */
  horsepower?: number | null;
  /** @nullable */
  transmission_id?: number | null;
  /** @nullable */
  fuel_type_id?: number | null;
  /** @nullable */
  color_id?: number | null;
  condition_id: number;
  /** @nullable */
  vin?: string | null;
  price: number;
  currency: VehicleInputCurrency;
  is_negotiable?: boolean;
  /** @nullable */
  description?: string | null;
  region_id: number;
  city_id: number;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  status?: VehicleInputStatus;
}
